---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elastic-es-default-es-config
  namespace: ${releaseNamespace}
data:
  values.yaml: |-
    cluster:
      name: elastic
      routing:
        allocation:
          awareness:
            attributes: k8s_node_name
    discovery:
      seed_providers: file
    http:
      publish_host: ${POD_NAME}.${HEADLESS_SERVICE_NAME}.${NAMESPACE}.svc
    network:
      host: "0"
      publish_host: ${POD_IP}
    node:
      attr:
        k8s_node_name: ${NODE_NAME}
      name: ${POD_NAME}
      store:
        allow_mmap: false
    path:
      data: /usr/share/elasticsearch/data
      logs: /usr/share/elasticsearch/logs
    xpack:
      license:
        upload:
          types:
          - trial
          - enterprise
      security:
        authc:
          realms:
            file:
              file1:
                order: -100
            native:
              native1:
                order: -99
          reserved_realm:
            enabled: "false"
        enabled: "true"
        http:
          ssl:
            certificate: /usr/share/elasticsearch/config/http-certs/tls.crt
            certificate_authorities: /usr/share/elasticsearch/config/http-certs/ca.crt
            enabled: false
            key: /usr/share/elasticsearch/config/http-certs/tls.key
        transport:
          ssl:
            certificate: /usr/share/elasticsearch/config/node-transport-cert/transport.tls.crt
            certificate_authorities:
            - /usr/share/elasticsearch/config/transport-certs/ca.crt
            - /usr/share/elasticsearch/config/transport-remote-certs/ca.crt
            enabled: "true"
            key: /usr/share/elasticsearch/config/node-transport-cert/transport.tls.key
            verification_mode: certificate
