---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zookeeper-kafka
  namespace: ${releaseNamespace}
spec:
  chart:
    spec:
      chart: zookeeper
      version: 10.2.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: ${releaseNamespace}
  interval: 15s
  install:
    remediation:
      retries: 30
    createNamespace: false
  upgrade:
    remediation:
      retries: 30
  targetNamespace: ${releaseNamespace}
  valuesFrom:
  - kind: ConfigMap
    name: zookeeper-kafka-defaults