import streamlit as st

st.set_page_config(
    page_title="DKP Streamlit Application",
    page_icon="🧊",
    layout="wide",
    initial_sidebar_state="expanded",
)

st.title("Welcome to Streamlit")

st.text("Create a config map  called streamlit-config in this namespace with 2 x keys:")
st.text("A key called app, the value of which should be your streamlit python code")
st.text("A key called requirements. This should contain your python library requirements which can be generated by running 'pip freeze'")