apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test
  namespace: nifi
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ebs-sc
  volumeMode: Filesystem
